site_name: Programación Avanzada Python Backend - FastAPI
site_url: https://jfinfosena.github.io/25pap/
site_author: jhonfvg

theme:
  name: material
  language: es  
  icon:
    logo: octicons/code-16    
  features:    
    - navigation.tabs.sticky 
    - navigation.tabs
    - navigation.top
    # - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
  palette:    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode        

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false  

copyright: 2025 &copy; by JFVG

nav:
  - Inicio: index.md  
  - Contenido:    
      - content/p1.md    
      - content/p2.md    
      - content/p3.md    
      - content/p4.md 
      - content/p5.md 
      - content/p6.md 
      - content/p7.md 
      - content/p8.md 
      - content/p9.md 

  - Actividades: 
      - activities/p1.md         

  - Tutoriales: 
      - tutorial/p1.md     
      - tutorial/p2.md     
      - tutorial/p3.md     
      - tutorial/p4.md     
      - tutorial/p5.md 
      - Sistema de Inventario con FastAPI: 
        - tutorial/api1/01-introduccion-fastapi.md
        - tutorial/api1/02-instalacion-configuracion.md  
        - tutorial/api1/03-estructura-proyecto.md  
        - tutorial/api1/04-base-datos-sqlalchemy.md       
        - tutorial/api1/05-esquemas-pydantic.md      
        - tutorial/api1/06-operaciones-crud.md      
        - tutorial/api1/07-endpoints-routers.md     
        - tutorial/api1/08-middleware-autenticacion.md      
        - tutorial/api1/09-testing-pruebas.md  
        - tutorial/api1/10-deployment-produccion.md       
        - tutorial/api1/11-Repositorio.md       
      - Ejemplo Básico FastAPI: 
        - tutorial/api2/01-introduccion.md
        - tutorial/api2/02-configuracion-entorno.md 
        - tutorial/api2/03-estructura-proyecto.md 
        - tutorial/api2/04-base-datos-modelos.md       
        - tutorial/api2/05-esquemas-validacion.md     
        - tutorial/api2/06-operaciones-crud.md      
        - tutorial/api2/07-rutas-endpoints.md    
        - tutorial/api2/08-aplicacion-principal.md      
        - tutorial/api2/09-testing-debugging.md
        - tutorial/api2/10-documentacion-deployment.md       
        - tutorial/api2/11-Repositorio.md      
     

plugins:
  - search
  # - blog
  - glightbox


